name: quizzly
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/pictures/



  fonts:
    - family: ExpletusSans
      fonts:
        - asset: assets/fonts/ExpletusSans-Bold.ttf
          weight: 700

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans_18pt-Black.ttf
          weight: 700
        - asset: assets/fonts/DMSans_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans_24pt-Medium.ttf
          weight: 500

